set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 16) # API level
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_STL_TYPE c++_static)
set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang)
set(CMAKE_ANDROID_ARM_NEON ON)